In [48]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import matplotlib.axes as axes
import torch
import random
import os

In [49]:
def linear_regression(X, w, b):
    return torch.matmul(X, w) + b

def squared_loss(y_predict, y):
    return (y_predict - y.reshape(y_predict.shape)) ** 2 / 2

def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices, :], labels[batch_indices]

def sgd(params, learning_rate, batch_size):
    with torch.no_grad():
        for param in params:
            param -= learning_rate * param.grad / batch_size
            param.grad.zero_()


In [79]:
dataset = pd.read_csv( "1000_Companies.csv")
dataset.drop("State", axis=1, inplace=True)
inputs, outputs = dataset.iloc[:, :-1], dataset.iloc[:, -1]
features_train, features_test, labels_train, labels_test = train_test_split(inputs, outputs, test_size=0.2, random_state=2024)

In [90]:
w = torch.normal(0, 0.01, size=(3, 1), requires_grad=True, dtype=torch.double)
b = torch.zeros(1, requires_grad=True)
batch_size = 80
lr = 0.1
num_epoch = 3
net = linear_regression
loss = squared_loss

for epoch in range(num_epoch):
    for X, y in data_iter(batch_size,torch.from_numpy(features_train.values),
                      torch.from_numpy(labels_train.values.reshape((-1,1)))):
        l = loss(net(X, w, b), y)
        l.sum().backward()
        sgd([w, b], lr, batch_size)
        print(w)
    with torch.no_grad():
        train_l = loss(net(X, w, b), y)
        print(f'epoch:{epoch + 1}, loss:{float(train_l.mean()):f}')

tensor([[1.1259e+09],
        [1.4516e+09],
        [2.9642e+09]], dtype=torch.float64, requires_grad=True)
tensor([[-9.9413e+18],
        [-1.2219e+19],
        [-2.6105e+19]], dtype=torch.float64, requires_grad=True)
tensor([[8.3939e+28],
        [1.0523e+29],
        [2.2166e+29]], dtype=torch.float64, requires_grad=True)
tensor([[-8.4630e+38],
        [-9.6893e+38],
        [-2.1354e+39]], dtype=torch.float64, requires_grad=True)
tensor([[5.3771e+48],
        [7.6186e+48],
        [1.4591e+49]], dtype=torch.float64, requires_grad=True)
tensor([[-inf],
        [-inf],
        [-inf]], dtype=torch.float64, requires_grad=True)
tensor([[nan],
        [nan],
        [nan]], dtype=torch.float64, requires_grad=True)
tensor([[nan],
        [nan],
        [nan]], dtype=torch.float64, requires_grad=True)
tensor([[nan],
        [nan],
        [nan]], dtype=torch.float64, requires_grad=True)
tensor([[nan],
        [nan],
        [nan]], dtype=torch.float64, requires_grad=True)
epoch:1, loss:na