In [1]:
import torch
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

# 张量与线性代数

In [53]:
# 张量的创建
A = torch.arange(12).reshape(3,4)
B = torch.tensor([[1,2,3,9],[4,5,6,8],[0,1,2,0]])
numpy_ = np.array([[1,2,3,9],[4,5,6,8],[0,1,2,0]], dtype='float')
C = torch.tensor(numpy_)
A, B, C, A + 1, A + B, A * B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[1, 2, 3, 9],
         [4, 5, 6, 8],
         [0, 1, 2, 0]]),
 tensor([[1., 2., 3., 9.],
         [4., 5., 6., 8.],
         [0., 1., 2., 0.]], dtype=torch.float64),
 tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([[ 1,  3,  5, 12],
         [ 8, 10, 12, 15],
         [ 8, 10, 12, 11]]),
 tensor([[ 0,  2,  6, 27],
         [16, 25, 36, 56],
         [ 0,  9, 20,  0]]))

In [60]:
# 点积
x = torch.ones(4, dtype=torch.float32)
y = torch.arange(4, dtype=torch.float32)
print(x, y)
print(x * y)
torch.dot(x, y)

tensor([1., 1., 1., 1.]) tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


tensor(6.)

In [77]:
# 矩阵与向量的乘积
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(x)
print(A)
torch.mv(A, x)

tensor([1., 1., 1., 1.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([ 6., 22., 38.])

In [81]:
# 矩阵与矩阵
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
B = torch.arange(12, dtype=torch.float32).reshape(4,3)
print(A)
print(B)
torch.mm(A,B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

In [90]:
# 范数
print(A)
print('L2范数:',A.norm())
print('L2范数:',A.norm(dim=0))
print('L1范数:',A.abs().sum())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
L2范数: tensor(22.4944)
L2范数: tensor([ 8.9443, 10.3441, 11.8322, 13.3791])
L1范数: tensor(66.)


# 自动微分

In [57]:
# 自动微分
x = torch.arange(4.0, requires_grad=True)
# 定义y
y = 2*torch.dot(x,x)
y.backward()  # 求导
x_grad = x.grad
print(x)
print(y)
print(x_grad)

tensor([0., 1., 2., 3.], requires_grad=True)
tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])


In [67]:
# 非标量变量的反向传播
# 清除导数
x.grad.zero_()
# 定义y
y = x.sum()
# 求导
y.backward()
x_grad = x.grad
print(x)
print(y)
print(x_grad)

tensor([0., 1., 2., 3.], requires_grad=True)
tensor(6., grad_fn=<SumBackward0>)
tensor([1., 1., 1., 1.])


In [87]:
# python控制流的梯度算法
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()